### ISSUE TITLE
install error when installing on windows 10 32 bit 

### ISSUE THREAD

**Issue by vase070** [lindstrm/twitcha#15]
this is the error i get when trying to install 

`2016-08-02 21:48:54> Program: Starting Squirrel Updater: --install .
2016-08-02 21:48:55> Program: Starting install, writing to C:\Users\Vase\AppData\Local\SquirrelTemp
2016-08-02 21:48:55> Program: About to install to: C:\Users\Vase\AppData\Local\twitcha
2016-08-02 21:48:57> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Vase\AppData\Local\twitcha\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2016-08-02 21:48:57> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Vase\AppData\Local\twitcha\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-08-02 21:48:57> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Vase\AppData\Local\SquirrelTemp
2016-08-02 21:48:57> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-08-02 21:48:58> ApplyReleasesImpl: Writing files to app directory: C:\Users\Vase\AppData\Local\twitcha\app-2.1.6
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\content_shell.pak to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\content_shell.pak
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\content_resources_200_percent.pak to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\content_resources_200_percent.pak
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\d3dcompiler_47.dll to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\d3dcompiler_47.dll
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\ffmpeg.dll to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\ffmpeg.dll
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\icudtl.dat to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\icudtl.dat
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\libEGL.dll to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\libEGL.dll
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\libGLESv2.dll to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\libGLESv2.dll
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\LICENSE to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\LICENSE
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\natives_blob.bin to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\natives_blob.bin
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\node.dll to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\node.dll
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\snapshot_blob.bin to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\snapshot_blob.bin
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\squirrel.exe to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\squirrel.exe
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\twitcha.exe to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\twitcha.exe
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\ui_resources_200_percent.pak to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\ui_resources_200_percent.pak
2016-08-02 21:49:32> ApplyReleasesImpl: Moving file C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\lib\net45\xinput1_3.dll to C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\xinput1_3.dll
2016-08-02 21:49:42> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\twitcha.exe]
2016-08-02 21:49:42> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\Vase\AppData\Local\twitcha\app-2.1.6\twitcha.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassdc.<<invokePostInstall>b__d0>d__de.MoveNext()
2016-08-02 21:49:42> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>b__d6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__e2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
2016-08-02 21:49:43> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>b__d6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__e2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>b__d6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__e2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()<---`

**Comment by FlameCRO** [comment]
I am having the same issues. Can you please review it and fix it please
Love the app

**Comment by FlameCRO** [comment]
i have contacted you thru email aswell with my error code. hope you manage and fix it
